server:
  port: 8061

spring:
  application:
    name: auth-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8060/realms/taxi
          jwk-set-uri: http://localhost:8060/realms/taxi/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    "*": INFO
  config: classpath:log4j2.xml