server:
  port: 8061

spring:
  application:
    name: auth-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.server-url}/realms/taxi-realm
          jwk-set-uri: ${keycloak.server-url}/protocol/openid-connect/certs

service:
  passenger:
    url: ${PASSENGER_SERVICE_URL:http://localhost:8080/api/v1/passengers}
  driver:
    url: ${DRIVER_SERVICE_URL:http://localhost:8081/api/v1/drivers}

keycloak:
  client-id: taxi-client
  realm: taxi-realm
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
  server-url: ${KEYCLOAK_SERVER_URL:http://localhost:8060}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka
  instance:
    prefer-ip-address: true
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    "*": INFO
  config: classpath:log4j2.xml