version: '3.8'
services:
  passenger-service:
    build: ./passenger-service
    ports:
      - "8080:8080"
    depends_on:
      - passenger-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://passenger-db:5432/passenger_db
      SPRING_DATASOURCE_USERNAME: simakkoi
      SPRING_DATASOURCE_PASSWORD: 4130

  driver-service:
    build: ./driver-service
    ports:
      - "8081:8081"
    depends_on:
      - driver-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://driver-db:5432/driver_db
      SPRING_DATASOURCE_USERNAME: simakkoi
      SPRING_DATASOURCE_PASSWORD: 4130
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  rides-service:
    build: ./rides-service
    ports:
      - "8082:8082"
    depends_on:
      - rides-db
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://rides-db:27017/rides_db
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      CLOUD_OPENFEIGN_CLIENT_CONFIG_PASSENGER_CLIENT_URL: http://passenger-service:8080/api/v1/passengers

  rating-service:
    build:
      context: ./rating-service
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8083:8083"
    depends_on:
      - rating-db
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://rating-db:5432/rating_db
      QUARKUS_DATASOURCE_USERNAME: simakkoi
      QUARKUS_DATASOURCE_PASSWORD: 4130
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      QUARKUS_REST_CLIENT_RIDESCLIENT_URL: http://rides-service:8082/api/v1

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  passenger-db:
    image: postgres:16
    environment:
      POSTGRES_DB: passenger_db
      POSTGRES_USER: simakkoi
      POSTGRES_PASSWORD: 4130
    ports:
      - "5433:5432"
    volumes:
      - passenger_db_data:/var/lib/postgresql/data

  driver-db:
    image: postgres:16
    environment:
      POSTGRES_DB: driver_db
      POSTGRES_USER: simakkoi
      POSTGRES_PASSWORD: 4130
    ports:
      - "5434:5432"
    volumes:
      - driver_db_data:/var/lib/postgresql/data

  rides-db:
    image: mongo:6
    ports:
      - "27018:27017"
    volumes:
      - rides_db_data:/data/db

  rating-db:
    image: postgres:16
    environment:
      POSTGRES_DB: rating_db
      POSTGRES_USER: simakkoi
      POSTGRES_PASSWORD: 4130
    ports:
      - "5435:5432"
    volumes:
      - rating_db_data:/var/lib/postgresql/data


volumes:
  passenger_db_data:
  driver_db_data:
  rides_db_data:
  rating_db_data: