version: '3.8'
services:
  passenger-service:
    build: ./passenger-service
    ports:
      - "8080:8080"
    depends_on:
      - passenger-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://passenger-db:5432/passenger_db
      SPRING_DATASOURCE_USERNAME: simakkoi
      SPRING_DATASOURCE_PASSWORD: 4130

  driver-service:
    build: ./driver-service
    ports:
      - "8081:8081"
    depends_on:
      - driver-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://driver-db:5432/driver_db
      SPRING_DATASOURCE_USERNAME: simakkoi
      SPRING_DATASOURCE_PASSWORD: 4130

  rides-service:
    build: ./rides-service
    ports:
      - "8082:8082"
    depends_on:
      - rides-db
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://rides-db:27017/rides_db

  rating-service:
    image: simakkoi/rating-service:1.0-SNAPSHOT
    ports:
      - "8083:8083"
    depends_on:
      - rating-db
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://rating-db:5432/rating_db
      QUARKUS_DATASOURCE_USERNAME: simakkoi
      QUARKUS_DATASOURCE_PASSWORD: 4130

  passenger-db:
    image: postgres:16
    environment:
      POSTGRES_DB: passenger_db
      POSTGRES_USER: simakkoi
      POSTGRES_PASSWORD: 4130
    ports:
      - "5433:5432"
    volumes:
      - passenger_db_data:/var/lib/postgresql/data

  driver-db:
    image: postgres:16
    environment:
      POSTGRES_DB: driver_db
      POSTGRES_USER: simakkoi
      POSTGRES_PASSWORD: 4130
    ports:
      - "5434:5432"
    volumes:
      - driver_db_data:/var/lib/postgresql/data

  rides-db:
    image: mongo:6
    ports:
      - "27018:27017"
    volumes:
      - rides_db_data:/data/db

  rating-db:
    image: postgres:16
    environment:
      POSTGRES_DB: rating_db
      POSTGRES_USER: simakkoi
      POSTGRES_PASSWORD: 4130
    ports:
      - "5435:5432"
    volumes:
      - rating_db_data:/var/lib/postgresql/data

volumes:
  passenger_db_data:
  driver_db_data:
  rides_db_data:
  rating_db_data: