server:
  port: 8082

spring:
  application:
    name: rides-service

  liquibase:
    change-log: classpath:db/changelog/main-changelog.yaml
    enabled: false

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

fare:
  start: 3
  per-km: 2.5

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka}

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 90
        slowCallDurationThreshold: 3s
        minimumNumberOfCalls: 3
        permittedNumberOfCallsInHalfOpenState: 3
        sliding-window-type: COUNT_BASED
        slidingWindowSize: 10
        waitDurationInOpenState: 10s
        automaticTransitionFromOpenToHalfOpenEnabled: true
        ignore-exceptions:
          - io.simakkoi9.ridesservice.exception.PassengerNotFoundException
    instances:
      passengerCircuitBreaker:
        base-config: default

  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 500ms
        ignore-exceptions:
          - io.simakkoi9.ridesservice.exception.PassengerNotFoundException
    instances:
      passengerServiceRetry:
        base-config: default

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    circuitbreakers:
      enabled: true
  metrics:
    tags:
      application: rides-service
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    tracing:
      export:
        enabled: true
      endpoint: ${OTLP_ENDPOINT:http://tempo:4318}

logging:
  level:
    feign: DEBUG
    "*": INFO
  config: classpath:log4j2.xml