server:
  port: 8082

spring:
  profiles:
    active: dev
  application:
    name: rides-service

  liquibase:
    change-log: classpath:db/changelog/main-changelog.yaml
    enabled: false

fare:
  start: 3
  per-km: 2.5

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka