server:
  port: 8082

spring:
  application:
    name: rides-service

  liquibase:
    change-log: classpath:db/changelog/main-changelog.yaml
    enabled: false

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

fare:
  start: 3
  per-km: 2.5

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka}