server:
  port: 8082

spring:
  application:
    name: rides-service
  data:
    mongodb:
      uri: ${DB_URI:mongodb://simakkoi:4130@localhost:27017/rides_db}
  liquibase:
    change-log: classpath:db/changelog/main-changelog.yaml
    enabled: false
  cloud:
    openfeign:
      client:
        config:
          passenger-client:
            connectTimeout: 5000
            readTimeout: 10000
            url: http://localhost:8080/api/v1/passengers

fare:
  start: 3
  per-km: 2.5