server:
  port: 8082

spring:
  application:
    name: rides-service
  data:
    mongodb:
      uri: ${DB_URI:mongodb://simakkoi:4130@localhost:27017/rides_db}
  liquibase:
    change-log: classpath:db/changelog/main-changelog.yaml
    enabled: false