quarkus:
  datasource:
    db-kind: postgresql
    username: simakkoi
    password: 4130
    jdbc:
      url: jdbc:postgresql://localhost:5432/rating_db

  flyway:
    migrate-at-start: true
    locations: db/migration

  hibernate-orm:
    database:
      generation: validate

  http:
    port: 8083

  resteasy:
    jsonb: enabled