server:
  port: 8050

spring:
  application:
    name: gateway-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8060/realms/taxi-realm
      client:
        registration:
          keycloak:
            client-id: gateway
            client-secret: kDUNuNIxvOnWxIvHghtCO72FzANrBcsf
            scope: openid
            provider: keycloak
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8060/login/oauth2/code/keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:8060/realms/taxi-realm

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: passenger-service
          uri: lb://PASSENGER-SERVICE
          predicates:
            - Path=/api/v1/passengers/**

        - id: driver-service-drivers
          uri: lb://DRIVER-SERVICE
          predicates:
            - Path=/api/v1/drivers/**

        - id: driver-service-cars
          uri: lb://DRIVER-SERVICE
          predicates:
            - Path=/api/v1/cars/**

        - id: rides-service
          uri: lb://RIDES-SERVICE
          predicates:
            - Path=/api/v1/rides/**

        - id: rating-service
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/api/v1/ratings/**

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: gateway-service
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://tempo:9411/api/v2/spans}

logging:
  level:
    "*": INFO
  config: classpath:log4j2.xml