global:
  scrape_interval: 5s
  evaluation_interval: 5s

  external_labels:
    monitor: 'taxi'

scrape_configs:
  - job_name: 'eureka'
    eureka_sd_configs:
      - server: 'http://eureka-service:8761/eureka'
        refresh_interval: 10s

    relabel_configs:
      - source_labels: [ "__meta_eureka_app_instance_metadata_prometheus_path" ]
        action: replace
        target_label: __metrics_path__
        regex: (.+)

      - source_labels: [ __address__, __meta_eureka_app_instance_metadata_prometheus_port ]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__

      - source_labels: [__meta_eureka_app_name]
        target_label: job
