server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: "docker-containers"
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["com.docker.compose.project"]
    pipeline_stages:
      - docker: {}
      - regex:
          expression: '\[traceId=(?P<traceId>[0-9a-f]+)\s+spanId=[0-9a-f]+\]'
      - labels:
          traceId:
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'

  - job_name: "driver-service-logs"
    static_configs:
      - targets: [localhost]
        labels:
          app: "driver-service"
          component: "business-service"
          __path__: /var/lib/docker/containers/*driver-service*/*-json.log
    pipeline_stages:
      - docker: {}
      - regex:
          expression: '\[traceId=(?P<traceId>[0-9a-f]+)\s+spanId=[0-9a-f]+\]'
      - labels:
          traceId:

  - job_name: "passenger-service-logs"
    static_configs:
      - targets: [localhost]
        labels:
          app: "passenger-service"
          component: "business-service"
          __path__: /var/lib/docker/containers/*passenger-service*/*-json.log
    pipeline_stages:
      - docker: {}
      - regex:
          expression: '\[traceId=(?P<traceId>[0-9a-f]+)\s+spanId=[0-9a-f]+\]'
      - labels:
          traceId:

  - job_name: "rides-service-logs"
    static_configs:
      - targets: [localhost]
        labels:
          app: "rides-service"
          component: "business-service"
          __path__: /var/lib/docker/containers/*rides-service*/*-json.log
    pipeline_stages:
      - docker: {}
      - regex:
          expression: '\[traceId=(?P<traceId>[0-9a-f]+)\s+spanId=[0-9a-f]+\]'
      - labels:
          traceId:

  - job_name: "rating-service-logs"
    static_configs:
      - targets: [localhost]
        labels:
          app: "rating-service"
          component: "business-service"
          __path__: /var/lib/docker/containers/*rating-service*/*-json.log
    pipeline_stages:
      - docker: {}
      - regex:
          expression: '\[traceId=(?P<traceId>[0-9a-f]+)\s+spanId=[0-9a-f]+\]'
      - labels:
          traceId:

  - job_name: "eureka-service-logs"
    static_configs:
      - targets: [localhost]
        labels:
          app: "eureka-service"
          component: "discovery"
          __path__: /var/lib/docker/containers/*eureka-service*/*-json.log
    pipeline_stages:
      - docker: {}
      - regex:
          expression: '\[traceId=(?P<traceId>[0-9a-f]+)\s+spanId=[0-9a-f]+\]'
      - labels:
          traceId:

  - job_name: "gateway-service-logs"
    static_configs:
      - targets: [localhost]
        labels:
          app: "gateway-service"
          component: "api-gateway"
          __path__: /var/lib/docker/containers/*gateway-service*/*-json.log
    pipeline_stages:
      - docker: {}
      - regex:
          expression: '\[traceId=(?P<traceId>[0-9a-f]+)\s+spanId=[0-9a-f]+\]'
      - labels:
          traceId:

  - job_name: "database-logs"
    static_configs:
      - targets: [localhost]
        labels:
          component: "database"
          __path__: /var/lib/docker/containers/*postgres*/*-json.log,/var/lib/docker/containers/*rides-db*/*-json.log
    pipeline_stages:
      - docker: {}
      - regex:
          expression: '\[traceId=(?P<traceId>[0-9a-f]+)\s+spanId=[0-9a-f]+\]'
      - labels:
          traceId: