server:
  port: 8081

spring:
  application:
    name: driver-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/driver_db}
    username: ${DB_USERNAME:simakkoi}
    password: ${DB_PASSWORD:4130}

  liquibase:
    change-log: classpath:/db/changelog/main-changelog.yaml

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka}