server:
  port: 8761

spring:
  application:
    name: eureka-service

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    tracing:
      export:
        enabled: true
      endpoint: ${OTLP_ENDPOINT:http://otel-collector:4318}

logging:
  level:
    "*": INFO