server:
  port: 8080

spring:
  application:
    name: passenger-service

  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/passenger_db}
    username: ${DB_USERNAME:simakkoi}
    password: ${DB_PASSWORD:4130}

  liquibase:
    change-log: classpath:/db/changelog/main-changelog.yaml
