server:
  port: 8080

spring:
  application:
    name: passenger-service

  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}

  liquibase:
    change-log: classpath:/db/changelog/main-changelog.yaml
